attention_type: None
sr_model: options/rafd/auto_encoder.yaml
n_input_modal: 7
name: multi_modal_no_attention
dataroot: ./dataset/RaFD090Crop
dataset: rafd
targetp: ['28', '47', '53', '57', '70', '73']
dataset_mode: all
model: collaborative_attention
input_nc: 3
output_nc: 3
batch_size: 2
beta1: 0.5
checkpoints_dir: ./checkpoints
continue_train: False
crop_size: 256
direction: AtoB
display_env: main
display_freq: 400
display_id: 1
display_ncols: 4
display_port: 8097
display_server: http://localhost
display_winsize: 256
epoch: 100
epoch_count: 1
gan_mode: vanilla
gpu_ids: [0]
init_gain: 0.02
init_type: normal
isTrain: True
lambda_L1: 100.0
load_iter: 0
load_size: 286
lr: 0.0002
lr_decay_iters: 50
lr_policy: linear
max_dataset_size: 1000000
n_epochs: 200
n_epochs_decay: 0
n_layers_D: 3
ndf: 64
netD: basic
netG: mh_resnet_6blocks
ngf: 64
no_dropout: False
no_flip: False
no_html: False
norm: batch
num_threads: 4
phase: train
pool_size: 0
preprocess: resize_and_crop
print_freq: 100
save_by_iter: False
save_epoch_freq: 50
save_latest_freq: 5000
serial_batches: False
split: train
suffix: None
update_html_freq: 1000
verbose: False